import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { EditorComponent, TINYMCE_SCRIPT_SRC } from '@tinymce/tinymce-angular';

@Component({
  selector: 'app-tinymce-self-hosted',
  standalone: true,
  imports: [EditorComponent, FormsModule],
  providers: [
    { provide: TINYMCE_SCRIPT_SRC, useValue: 'tinymce/tinymce.min.js' },
  ],
  templateUrl: './tinymce-self-hosted.component.html',
  styleUrl: './tinymce-self-hosted.component.scss',
})
export class TinymceSelfHostedComponent {
  htmlContent = signal<string>(
    `
    <div class="WordSection1">
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; margin: 0in -28.35pt 32.65pt -.45pt;" align="left"><a name="_Hlk34923348"></a><span lang="EN-GB" style="mso-no-proof: yes;"> </span><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><strong><span lang="EN-GB" style="font-size: 10.5pt; line-height: 107%;">CASH COLLECTION AGREEMENT</span></strong></p>
<p class="MsoNormal" style="text-indent: 0in; margin: 0in 0in 9.4pt 0in;"><span lang="EN-GB">Between<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>And</span></p>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; tab-stops: 139.3pt 162.2pt; margin: 0in 45.0pt 9.25pt 9.0pt;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">STANBIC BANK GHANA LTD<span style="mso-tab-count: 4;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></strong><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB" style="color: #4472c4;">Gigi</span></strong></p>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; tab-stops: 139.3pt 162.2pt; margin: 0in 0in 9.25pt 9.0pt;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">Stanbic Heights Plot No. 215 North<span style="mso-spacerun: yes;">&nbsp; </span></span></strong><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB" style="color: #4472c4;"><span style="mso-tab-count: 3;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>3004<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></strong></p>
<p class="MsoNormal" style="text-align: left; text-indent: -279.0pt; line-height: 107%; tab-stops: 139.3pt 162.2pt; margin: 0in 0in 9.25pt 4.0in;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">Liberation Link Airport City Accra<span style="mso-tab-count: 1;"> </span><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></strong><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB" style="color: #4472c4;">of Gigi3 </span></strong></p>
<p class="MsoNormal" style="text-align: left; text-indent: -.5pt; line-height: 107%; tab-stops: 139.3pt 162.2pt; margin: 0in 0in 9.25pt -.25pt;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB"><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>(the Bank) <span style="mso-tab-count: 5;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span></strong><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB" style="color: #4472c4;">Limited Liability Company </span></strong></p>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; tab-stops: 139.3pt 162.2pt; margin: 0in -3.5in .2pt 0in;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB" style="color: #4472c4;"><span style="mso-tab-count: 6;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-spacerun: yes;">&nbsp;</span>(The Customer)</span></strong></p>
</div>
<p><span lang="EN-GB" style="font-size: 8.0pt; mso-bidi-font-size: 11.0pt; line-height: 105%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial; color: #0066b3; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB; mso-bidi-language: AR-SA;">&nbsp;</span></p>
<div class="WordSection2">
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; margin: 0in -3.5in .2pt 0in;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB" style="color: #4472c4;"><span style="mso-tab-count: 5;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></strong></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; line-height: 107%;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB" style="color: #4472c4;">&nbsp;</span></strong></p>
</div>
<p><span lang="EN-GB" style="font-size: 8.0pt; mso-bidi-font-size: 11.0pt; line-height: 105%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial; color: #0066b3; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB; mso-bidi-language: AR-SA;">&nbsp;</span></p>
<div class="WordSection3">
<p class="MsoNormal" style="margin-left: -.25pt; text-align: left; text-indent: -.5pt; line-height: 107%;" align="left"><span lang="EN-GB" style="color: #4472c4;">&nbsp;</span></p>
<p class="MsoNormal" style="margin-left: -.25pt; text-align: left; text-indent: -.5pt; line-height: 107%;" align="left"><span lang="EN-GB">&nbsp;</span></p>
</div>
<p><span lang="EN-GB" style="font-size: 8.0pt; mso-bidi-font-size: 11.0pt; line-height: 105%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial; color: #0066b3; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB; mso-bidi-language: AR-SA;">&nbsp;</span></p>
<div class="WordSection4">
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 59.35pt;"><span lang="EN-GB">1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>DEFINITIONS</span></h2>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>In this Agreement, unless clearly inconsistent with or indicated otherwise by the context:</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Ad-hoc services</strong> means additional Cash Collection Services requested by the Customer from time to time;</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Agreement</strong> means the agreement set out in this document including all Appendices hereto; to it as well as any future amendments as agreed in writing between the Parties.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.3<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> <strong style="mso-bidi-font-weight: normal;">Authorized Representative</strong> of either Party shall be a person bearing an identity card or other similar documents issued by the relevant party specifically designated by the relevant party for the purposes of this Agreement; </span></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: right 265.5pt;" align="left"><span lang="EN-GB">1.1.4<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Appendices </strong><span style="mso-spacerun: yes;">&nbsp;</span>means any document approved in writing by the </span></p>
<p class="MsoNormal" style="margin-left: 34.0pt; text-indent: 0in;"><span lang="EN-GB">Parties, which is incorporated in this Agreement from time to time. The appendices may be amended from time to time, in writing by mutual agreement between the Parties. </span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.5<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Bank</strong> means Stanbic Bank Ghana LTD (Registration Number CS659892015) a private company duly incorporated with limited liability according to the company laws of Ghana.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.6 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Business Day</strong> means a day when banks are open for business, <span style="mso-spacerun: yes;">&nbsp;</span>including, <span style="mso-spacerun: yes;">&nbsp;</span>a public holiday in Ghana, Saturday or Sunday, when requested in writing by the Customer.</span></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: right 265.5pt;" align="left"><span lang="EN-GB">1.1.7<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Cash</strong> means currency in notes or coins, or cheques, bankers </span></p>
<p class="MsoNormal" style="margin-left: 34.0pt; text-indent: 0in;"><span lang="EN-GB">draft or other similar instruments </span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.8 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Cash Centre</strong> means the Bank or its representative cash centre or branch.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.9 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Cash In Transit Services</strong> means the Cash collection services including the provision of a banking collection and delivery service, which entails Cross Pavement Transfer and In Transit at the frequency set out in <strong style="mso-bidi-font-weight: normal;">Annexure A</strong>.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.10<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span> <strong style="mso-bidi-font-weight: normal;">Incident</strong> means any theft, attempted theft or such other incident involving the Cash;</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.11<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">CIT Company</strong> means the cash in transit company providing the Cash In Transit Services.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.12<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Confidential Information</strong> means all information (written, oral or electronic) disclosed by one Party (<strong style="mso-bidi-font-weight: normal;">Disclosing Party</strong>) to the other Party, whether before or after the Effective Date, concerning the business affairs of the Disclosing Party, including any information relating to the Disclosing Party&rsquo;s operations, processes, plans, intentions, product information, know-how, designs, trade secrets, software, market opportunities, customers, data, reports, records and any other information of any kind whatsoever developed or acquired by either Party in connection with this Agreement and shall include the terms of this Agreement.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.13<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Container</strong> means a secure tamper evident container that is approved by the CIT Company, which includes a bag or canister, and into which the Money is placed.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.14 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Cross Pavement Carrier</strong> means the safety unit used by the CIT Company for Cross Pavement Transfer of the Money.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.15<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Cross Pavement Transfer </strong>means the transport of the Cross Pavement Carrier from the Site to the CIT vehicle and/or from the CIT vehicle to the Site.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.16 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Cross Pavement Value </strong>means the maximum amount indicated by the Bank in the Operations Manual for Cross Pavement Transfer of the Cash.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.17<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Customer</strong> means <strong>Gigi</strong> Registration number:</span><span lang="EN-GB" style="color: #4472c4; mso-themecolor: accent1;"> <strong>3004</strong></span><span lang="EN-GB">, a company duly incorporated in accordance with the laws of Ghana and herein represented by <strong>Gigi2 i</strong>n his/her capacity as Director, he/she being duly authorised hereto.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.18 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Deposit Book</strong> means the book issued to the Customer by the Bank from time to time for the deposit of Cash into the Customer&rsquo;s </span></p>
<p class="MsoNormal" style="margin-left: 34.0pt; text-indent: 0in;"><span lang="EN-GB">account held with the Bank;</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.19<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Effective Date</strong> means <strong>2023-09-13T00:00:00.000Z </strong>notwithstanding the date of signature of this Agreement by the last signing Party.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.20 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Fees</strong> means the monthly fees due to the Bank by the Customer for the Cash In Transit Services as set out in Appendix 2.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.21 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Group </strong>means Standard Bank Group Limited, its subsidiaries and their subsidiaries.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.22<strong style="mso-bidi-font-weight: normal;"> <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>Initial Period</strong> means one year commencing on the Effective Date.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.1.23 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">In Transit</strong> means any conveyance, movement or transportation of the Money in the CIT vehicle to the Cash Centre or from the Cash Centre and whilst in the CIT vehicle until it reaches the Site excluding Cross Pavement Transfer but including when the money is contained in the Cross Pavement Carrier <strong style="mso-bidi-font-weight: normal;">Cash </strong><span style="mso-bidi-font-weight: bold;">Collection Procedure means the appendix or schedule incorporated in the Agreement and detailing the processes and procedures for the collection of cash. </span></span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB" style="mso-bidi-font-weight: bold;">1.1.24 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span></span><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">Parties</span></strong><span lang="EN-GB" style="mso-bidi-font-weight: bold;"> means the Bank and the Customer, and each individual shall be referred to as the Party;</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB" style="mso-bidi-font-weight: bold;">1.1.25<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">Site</span></strong><span lang="EN-GB" style="mso-bidi-font-weight: bold;"> means the place(s) at which the Customer conducts its business or in future may conduct its business from and to which the Cash In Transit Services</span><span lang="EN-GB"> shall be rendered and which Sites are set out in the Operations Manual.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Expressions defined in this Agreement shall bear the same meanings in any Annexure or schedule to this Agreement which do not themselves contain their own definitions.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Any reference in this Agreement to legislation or subordinate legislation is to legislation or subordinate legislation at the date of signature of this Agreement and as amended and/or re-enacted from time to time.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.4 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Words importing the singular shall include the plural, and vice versa, words importing the masculine gender shall include the feminine and neuter genders, and vice versa, and words importing natural persons shall include legal persons, and vice versa.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.5 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The word &ldquo;including&rdquo; and its other grammatical forms shall not limit the general effect of the words which precede it and shall be construed and interpreted without any limitation.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.6 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The head notes to the clauses to this Agreement are inserted for reference purposes only and shall not affect the interpretation of any of the provisions to which they relate.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.7 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>If any provision in the definition clause is a substantive provision conferring rights or imposing obligations on a Party, then even if the provision is contained in this clause, effect shall be given to it as if the provision were a substantive provision in the body of the Agreement.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">1.8 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>When any number of days is prescribed in this Agreement, same shall be reckoned exclusively of the first and inclusively of the last day unless the last day falls on a Sunday or public holiday, in which case the last day shall be the next succeeding day which is a Business Day. </span></p>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">1.9 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>No provision in this Agreement should be construed against or interpreted to the disadvantage of any Party by reason of such Party having or being deemed to have structured, drafted or introduced the provision.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 64.7pt;"><span lang="EN-GB">2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>INTRODUCTION</span></h2>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">2.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The Bank is licensed under the laws of Ghana to provide banking services including cash collection. The Customer appoints the Bank to provide it with the Cash In Transit Services at a fee, which appointment the Bank accepts under the terms of this Agreement. </span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">2.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The Customer acknowledges that the Cash In Transit Services provided by the Bank are not risk free and as such it is incumbent that Insurance is in place for the Term of this Agreement.<span style="mso-spacerun: yes;">&nbsp; </span></span></p>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; margin: 0in 0in .15pt 0in;" align="left"><span style="mso-spacerun: yes;">&nbsp;</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 54.85pt;"><span lang="EN-GB">3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>DURATION</span></h2>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>This Agreement shall be for an initial period of one year from the date of this Agreement after which it will continue until terminated by either Party upon giving one month&rsquo;s written notice to the other Party; but nothing shall prevent the Bank from terminating this Agreement forthwith if in its absolute opinion the Customer has committed a serious breach of its obligations hereunder of which breach the Bank has notified the Customer in writing and the Customer has failed to take appropriate steps to remedy within a reasonable period of time as determined by the Bank, in its absolute opinion.<span style="mso-spacerun: yes;">&nbsp; </span></span></p>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; margin: 0in 0in .15pt 0in;" align="left"><span style="mso-spacerun: yes;">&nbsp;</span></p>
<p class="MsoNormal" style="text-align: left; text-indent: -.5pt; line-height: 107%; mso-list: l0 level1 lfo1; margin: 0in 35.95pt .2pt 1.0pt;" align="left"><!-- [if !supportLists]--><strong><span lang="EN-GB" style="font-size: 7.5pt; mso-bidi-font-size: 8.0pt; line-height: 107%;"><span style="mso-list: Ignore;">4<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB" style="font-size: 7.0pt; line-height: 107%;">CUSTOMER&rsquo;S UNDERTAKINGS AND OBLIGATIONS </span></strong></p>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; margin: 0in 35.95pt .2pt .5pt;" align="left"><span lang="EN-GB">4.1<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The Customer shall:</span></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: center 105.6pt;" align="left"><span lang="EN-GB">4.1.1<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Observe the Cash Collection Procedure.</span></p>
<p class="MsoNormal" style="text-align: left; tab-stops: right 265.55pt;" align="left"><span lang="EN-GB">4.1.2<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span lang="EN-GB" style="mso-bidi-font-size: 8.0pt; line-height: 105%;">Not obstruct, hinder, or delay the Bank in providing the Services</span><span lang="EN-GB" style="font-size: 7.0pt; line-height: 105%;">.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">4.1.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Cooperate with the Bank to the fullest extent possible on the occurrence of an Incident.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">4.1.4 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Not use the Service for transporting any items or documents or material other than Cash/Cheque.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">4.1.5 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Give the Bank seven days&rsquo; notice when requesting for deposit books for use in accordance with the Agreement.</span></p>
<p class="MsoNormal"><span lang="EN-GB">4.2<span style="mso-spacerun: yes;">&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The Customer warrants to handle the CIT and/or Bank equipment and materials allocated to the Customer with diligence and care and only for the intended purpose of such item, equipment and/or material and the Customer shall not acquire ownership of or any other rights to any goods supplied or allocated to the Customer by the CIT Company and/or the Bank in terms of this Agreement.</span></p>
<p class="MsoNormal"><span lang="EN-GB">4.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The Customer warrants that there are no liens and/or other rights of retention over material which the CIT Company and/or the Bank provides or allocate to the Customer in terms of the Cash In Transit Services supplied by the CIT Company and/or the Bank to the Customer.</span></p>
<p class="MsoNormal"><span lang="EN-GB">4.4 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Where the Customer requests that an alternative CIT company be appointed, the Customer is required to notify the Bank not later than 90 days prior to the requested appointment.</span></p>
<p class="MsoNormal" style="margin-bottom: 9.8pt;"><span lang="EN-GB">4.5<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp; </span>The Customer will give the Bank seven days&rsquo; notice when requesting for Deposit Books.</span></p>
<p class="MsoNormal" style="margin-bottom: 9.8pt;"><span lang="EN-GB"><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-spacerun: yes;">&nbsp;</span></span></p>
<p class="MsoNormal" style="margin-right: 35.95pt; text-align: left; line-height: 107%;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">5<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>BANK&rsquo;S UNDERTAKINGS AND OBLIGATIONS</span></strong></p>
<p class="MsoNormal" style="margin-right: 35.95pt; text-align: left; line-height: 107%;" align="left"><span lang="EN-GB">5.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The Bank Shall:</span></p>
<p class="MsoListParagraph" style="text-indent: -.5in; mso-list: l1 level3 lfo3;"><!-- [if !supportLists]--><span style="mso-list: Ignore;">5.1.1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span lang="EN-GB">Provide the Services in accordance with the terms of this Agreement and in particular to ensure the Cash Collection Procedure is observed;</span></p>
<p class="MsoNormal"><span lang="EN-GB">5.1.2<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp; </span>Collect and remove the sales proceeds from the Site, through the Carrier after issuing and delivering to an authorised representative of the Customer a receipt bearing the Bank&rsquo;s stamp stating the amount of sales proceeds being collected, the date and time of collection and removal duly signed by the Customer&rsquo;s authorised representative.</span></p>
<p class="MsoNormal"><span lang="EN-GB">5.1.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Report every loss or theft of sales proceeds to an authorised representative of the Customer (the first of such report is to be made verbally and thereafter by written report within 24 hours) and to the police immediately after the loss or theft is discovered by or comes to the attention of the Bank. The Bank shall at all times use its best endeavours to co-operate with the Customer and the police in an attempt to establish the identity of the perpetrator and secure his prosecution ad conviction.</span></p>
<p class="MsoNormal"><span lang="EN-GB">5.1.4 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style="mso-spacerun: yes;">&nbsp;</span>Charge the Customer a fee for the Cash Collection Services under this . <span style="mso-spacerun: yes;">&nbsp;</span></span></p>
<p class="MsoNormal"><span lang="EN-GB">5.1.5<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Deposit Cash in Cedis or any convertible currency and credit the<span style="mso-spacerun: yes;">&nbsp;&nbsp; </span>Customer&rsquo;s account on the Business Day on which same was collected. For cheque payments, the Bank shall deposit the cheque into the Customer&rsquo;s account for clearing in accordance with normal banking practice unless otherwise advised by the Customer.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 43.55pt;"><span lang="EN-GB">6 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>RISK</span></h2>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">6.1<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> In the event that the money is collected from the Site, all risk in the money shall vest as follows:</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">6.1.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>risk in the Cash vests in the Bank, from the time the Cash is handed over and acknowledged in writing by the CIT Company;</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">6.1.2<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> risk in any cheques vests in the Customer, from the time the cheques are<span style="mso-spacerun: yes;">&nbsp; </span>handed over and acknowledged in writing by the CIT Company.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">6.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>In the event that the Cash is delivered to the Customer from the Cash Centre to the Site, risk vests in the Bank, from the time the Cash is handed over to the CIT Company until such time as the Cash is received and acknowledged in writing by the Customer.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">6.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Insurance Cover shall be taken out and maintained for the Term of this Agreement by the Client. The Insurance Cover will cover all Risk Events and/or damage to the Cash during Cross Pavement Transfer and whilst the Cash is In Transit. For purposes of this clause 6.3, Risk Events means on-Site Cash, cash heist, theft and robbery.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">6.4 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Subject to clause 4.1.3 above, if the Customer exceeds the Cross-Pavement Value, the Customer shall be liable for all losses and/or damages suffered. The Customer will be considered to be in breach of the Insurance, and there will be no claim against the <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Insurance in the event of loss and/or damage to the Cash.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">6.5 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>If any Cash exceeds the Site insurance limit, this will be a breach of the Insurance, and if the Customer claims against the Insurance in the event of loss and/or damage to the Cash, the maximum amount payable will be the Site insurance limit. The Customer shall be liable for all losses and/or damages suffered in excess of the Site insurance limit.</span></p>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">6.6 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Risk in cheques and/or any negotiable instruments shall at all times remain with the Customer. The Customer shall be responsible for preparing a schedule of the cheques and other negotiable instruments to be handed to the CIT Company. </span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 74.1pt;"><span lang="EN-GB">7 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>FEES AND PAYMENT</span></h2>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">7.1<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>In consideration for the Cash In Transit Services to be rendered by the Bank, the Customer shall pay the Bank the Fees and any other charges incurred as set out in <strong style="mso-bidi-font-weight: normal;">Appendix 2 </strong><span style="mso-spacerun: yes;">&nbsp;</span>or such increased charges as may from time to time become payable, monthly in advance, by no later than the 25th day of the month.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">7.2<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Notwithstanding the provisions of clause 7.1 above, the Customer may alternatively effect payment of the Fees by means of a debit order </span></p>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">7.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Fees and charges levied in terms of this Agreement shall be reviewed as part of the pricing process and shall be increased when necessary and as agreed by the Parties and recorded in writing.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 76.6pt;"><span lang="EN-GB">8 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>GENERAL INDEMNITY</span></h2>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Notwithstanding anything to the contrary, the Customer indemnifies the Bank against any liability, loss, damage and/or claims of whatsoever nature and howsoever arising, unless such loss or damage is caused by the Bank&rsquo;s gross negligence or wilful misconduct, which may be brought against the Bank by a third party in respect of, or in any way connected to the Cash In Transit Services as contemplated in this Agreement and/or the implementation of this Agreement.</span></p>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; margin: 0in 0in .15pt 0in;" align="left"><span style="mso-spacerun: yes;">&nbsp;</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 83.2pt;"><span lang="EN-GB">9 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>LIMITATION OF LIABILITY</span></h2>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: center 109.85pt;" align="left"><span lang="EN-GB">9.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The Bank shall not be held responsible for:</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">9.1.1<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> any direct losses, damages or expenses suffered, incurred or sustained as a result of the provision of the Cash In Transit Services; or</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">9.1.2<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> any discrepancies occasioned by any acts or omissions of whatsoever nature of employees of the Customer appointed to carry out the duties on behalf of the Customer.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">9.2<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> Where the Customer suffers any loss and/or damage to the Money pursuant to or during the provision of the Cash In Transit Services by the CIT Company provided that such loss and/or damage to the Money:</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">9.2.1<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> is as a direct result of the negligence of or theft by the CIT Company&rsquo;s employees, acting within the course and scope of their employment; and</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">9.2.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>occurs while the Money is in the custody of the CIT Company; the claim for damages in respect of the Cash shall lie as against the Insurance.</span></p>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">9.3<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Notwithstanding anything to the contrary contained in this Agreement, the Parties shall not be liable to each other for any indirect or consequential loss or damage, including without limitation, loss of profit, revenue, anticipated savings, business transactions or goodwill or other contracts whether arising from negligence or breach of contract.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 70.0pt;"><span lang="EN-GB">10 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>CONFIDENTIALITY</span></h2>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">10.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Except as otherwise provided in this clause, the Confidential Information shall be treated by the Parties as confidential. No Party shall reveal or otherwise disclose such Confidential Information to any third party without the prior written consent of the other Party hereto. The above restrictions shall not apply to the disclosure of necessary Confidential Information to employees and advisors of the Parties. Any third party that may become privy to such information shall first undertake in writing to protect the confidential nature thereof.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">10.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The confidentiality undertaking in this clause 10 shall not apply in respect of Confidential Information within the public domain or a Party&rsquo;s knowledge at the commencement of this Agreement or to the disclosure required to satisfy the order of a court of competent jurisdiction or to comply with the provisions of any law or regulation in force from time to time.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">10.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The Parties shall not at any time during the Term, release any statement to the press, or make any other public statement of any nature which could reasonably be expected to be published in any media regarding the relationship or the subject matter of this Agreement, without the prior written consent of the other Party, which consent shall not be unreasonably withheld.</span></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: center 138.3pt;" align="left"><span lang="EN-GB">10.4 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>This clause shall survive the termination of this Agreement.</span></p>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; margin: 0in 0in .15pt 0in;" align="left"><span style="mso-spacerun: yes;">&nbsp;</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 85.2pt;"><span lang="EN-GB">11 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>PERSONAL INFORMATION</span></h2>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: center 90.65pt;" align="left"><span lang="EN-GB">11.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>In this clause 11, a reference to:</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">11.1.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">We</strong>,<strong style="mso-bidi-font-weight: normal;"> Us</strong>, <strong style="mso-bidi-font-weight: normal;">Our</strong> means Stanbic Bank Ghana Limited, its successors and assigns;</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">11.1.2<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span> <strong style="mso-bidi-font-weight: normal;">Personal Information</strong> means Personal Information as defined by the applicable data protection laws and/or the Data Protection Act, 2012 (Act 843);</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">11.1.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span><strong style="mso-bidi-font-weight: normal;">Process</strong> means Process as defined by the applicable data protection laws and/or the Data Protection Act, 2012 (Act 843). </span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">11.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>You consent to Us to collect your Personal Information from you and where lawful and reasonable, from public sources for credit, fraud and compliance purposes, as well as the purposes set out below.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">11.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>If you provide Us with Personal Information about or on behalf of another person (including, but not limited to, related parties where applicable), you confirm that you are authorised to:</span></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: center 107.15pt;" align="left"><span lang="EN-GB">11.3.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>provide Us with the Personal Information;</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">11.3.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>consent on their behalf to the Processing of their Personal Information, in terms of this clause; and</span></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: center 109.6pt;" align="left"><span lang="EN-GB">11.3.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>receive any privacy notices on their behalf.</span></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: center 135.25pt;" align="left"><span lang="EN-GB">11.4 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>You consent to Us Processing your Personal Information:</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">11.4.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>to provide products and services to you in terms of this Agreement and any other products and services for which you may apply;</span></p>
<p class="MsoNormal" style="text-align: left; line-height: 102%; margin: 0in 0in 0in 33.75pt;" align="left"><span lang="EN-GB">11.4.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>to carry out statistical and other analyses to identify potential markets and trends, evaluate and improve Our business (this includes improving existing and developing new products and services);</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">11.4.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>in countries outside the country where it is necessary for Us to provide the products and services. These countries may not have the same data protection laws as the country where the products or services are provided, We will endeavour to request the receiving party to accept the privacy and/or confidential policies, obligations, processes and/or requirements;</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">11.4.4<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span> by sharing your Personal Information with Our third-party service providers, locally and outside the country where the products or services are provided, in order to provide Our services and/ or product to you. We will request that these 3rd party service providers accept Our privacy and/or confidential policies, obligations, processes and/or requirements, if they need access to any Personal Information to carry out their services; and</span></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: center 64.25pt;" align="left"><span lang="EN-GB">11.4.5 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>within the Group.</span></p>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">11.5<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> You will find Our Processing practices in the Group&rsquo;s and Our privacy statements. These statements are available on the Group&rsquo;s websites or on request.<span style="mso-spacerun: yes;">&nbsp; </span></span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 87.15pt;"><span lang="EN-GB">12 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>SUPERIOR FORCE EVENTS</span></h2>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">12.1<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> If either Party is prevented or restricted directly or indirectly from carrying out all or any of its obligations under this Agreement by any cause beyond the reasonable control of that Party, including, without limitations, acts of God, civil commotion, industry-related strikes, riots, insurrection, acts of government, fire, explosion, the elements, epidemics, governmental embargoes or like causes (<strong style="mso-bidi-font-weight: normal;">Superior Force Events</strong>), the affected Party shall, to the extent prevented, be relieved of its obligations under this Agreement during the period of the events. The affected Party shall not be liable for any delay or failure in the performance of any obligations under this Agreement or loss or damage either general, special or consequential which the other Party may suffer due to or resulting </span></p>
<p class="MsoNormal" style="margin-left: 34.0pt; text-indent: 0in;"><span lang="EN-GB">from the delay or failure, provided always that the affected Party gives written notice of the occurrence constituting Superior Force Events to the other Party within 24 hours.</span></p>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">12.2<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The Parties agree that, should Superior Force Event last more than 4 weeks, the Party who has not invoked Superior Force Events to excuse any non-performance of its obligations may terminate this Agreement by giving 10 days&rsquo; written notice to the other Party.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 87.65pt;"><span lang="EN-GB">13 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>NATURE OF RELATIONSHIP</span></h2>
<p class="MsoNormal" style="text-indent: 0in; margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">This Agreement does not create a partnership, joint venture or agency between the Parties and neither Party shall be liable for the debts of the other Party, howsoever incurred.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 51.1pt;"><span lang="EN-GB">14 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>BREACH</span></h2>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Should any Party (<strong style="mso-bidi-font-weight: normal;">Defaulting Party</strong>) commit a breach of any provision of this Agreement and fail to remedy such breach, or if the breach is not capable of remedy, fail to implement such other action acceptable to the other Party, within 14 (fourteen) days of receiving a written notice from the other Party (<strong style="mso-bidi-font-weight: normal;">Aggrieved Party</strong>) requiring the Defaulting Party to do so, the Aggrieved Party shall be entitled in addition to its other remedies in law or in terms of this Agreement to cancel this Agreement forthwith and without prejudice to its rights to claim damages; provided that if the Defaulting Party commits two or more breaches of any material provision of this Agreement in any 6 month period of this Agreement, the Aggrieved Party shall be entitled without prejudice to any of its other rights or remedies in law or under this Agreement to terminate this Agreement forthwith by notice in writing to the Defaulting Party.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 61.5pt;"><span lang="EN-GB">15 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>TERMINATION</span></h2>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: center 128.95pt;" align="left"><span lang="EN-GB">15.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Either Party may terminate this Agreement as follows:</span></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: center 39.8pt;" align="left"><span lang="EN-GB">15.1.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>; or</span></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: center 139.4pt;" align="left"><span lang="EN-GB">15.1.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>for any reason, on 30 days&rsquo; written notice to the other Party.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">15.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Notwithstanding anything to the contrary contained herein, either Party shall be entitled to terminate this Agreement immediately if the other Party:</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">15.2.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>takes steps to place itself, or is placed in liquidation, whether voluntary or compulsory or under business rescue proceedings in either case whether provisionally or finally; or</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">15.2.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>passes a resolution to commence business rescue proceedings, or if business rescue proceedings are otherwise commenced in respect of the other Party; or</span></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: center 124.7pt;" align="left"><span lang="EN-GB">15.2.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>takes steps to deregister itself or is deregistered; or</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">15.3<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> Notwithstanding the provisions of clause 3 above, the Bank shall be entitled within 30 days of the Effective Date, to terminate this Agreement in writing for whatsoever reason, in which event the Bank shall repay to the Customer all charges received in respect of which no Cash In Transit Services have been rendered.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">15.4 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Termination of this Agreement shall not relieve a Party of obligations imposed upon such Party by statute or regulation or by this Agreement prior to its termination.</span></p>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">15.5 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>If, for whatever reason, the Bank continues to provide the Cash In Transit Services to the Customer at any time after the date of termination of this Agreement, at the election of the Customer, the Bank shall do so on the same terms and conditions set out in this Agreement, for a limited period of time as agreed to between the Parties in writing.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 89.3pt;"><span lang="EN-GB">16 <span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>NOVATION </span></h2>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 89.3pt;"><span lang="EN-GB" style="font-weight: normal; mso-bidi-font-weight: bold;"><span style="mso-spacerun: yes;">&nbsp;</span>16.1</span><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span lang="EN-GB" style="font-weight: normal; mso-bidi-font-weight: bold;">This Agreement shall replace any and all prior existing</span></h2>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 89.3pt;"><span lang="EN-GB" style="font-weight: normal; mso-bidi-font-weight: bold;"><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>discussions and agreements between the Parties and shall </span></h2>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 89.3pt;"><span lang="EN-GB" style="font-weight: normal; mso-bidi-font-weight: bold;"><span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>take effect from the Effective Date as stated above.</span></h2>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 89.3pt;"><span lang="EN-GB">&nbsp;</span></h2>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 89.3pt;"><span lang="EN-GB">17.<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>CESSION AND ASSIGNMENT</span></h2>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">17.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Neither Party shall be entitled to cede, assign, transfer or make over any of their rights or obligations in terms of this Agreement without obtaining the prior written consent of the other Party.</span></p>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">16.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Any cession or assignment agreed to by the Bank shall not relieve the Customer of any obligations with respect to any covenant, condition, or obligation required to be performed by the Customer under this Agreement.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 105.05pt;"><span lang="EN-GB">18 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>IMPLEMENTATION AND GOOD FAITH</span></h2>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">18.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The Parties undertake to do all such things, perform all such acts and take all steps to procure the doing of all such things and the performance of all such acts, as may be necessary or incidental to give or conducive to the giving of effect to the terms, conditions and import of this Agreement.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">18.2<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span> The Parties shall at all times during the Term of this Agreement observe the principles of good faith towards one another in the performance of their obligations in terms of this Agreement.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">&nbsp;</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 68.45pt;"><span lang="EN-GB">19 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>GOVERNING LAW</span></h2>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The laws of Ghana shall govern the validity, interpretation and performance of this Agreement and the courts of Ghana shall have non-exclusive jurisdiction in the interpretation and enforcement of this Agreement. </span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 63.15pt;"><span lang="EN-GB">20 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>SEVERABILITY</span></h2>
<p class="MsoNormal" style="text-indent: 0in; margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">The invalidity, illegality, or unenforceability of any of the provisions of this Agreement shall not affect the validity, legality and enforceability of the remaining provisions of this Agreement.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 56.9pt;"><span lang="EN-GB">21 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>NO WAIVER</span></h2>
<p class="MsoNormal" style="text-indent: 0in; margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">The failure of either Party to insist upon the strict performance of any provision of this Agreement or to exercise any right, power or remedy consequent upon a breach hereof shall not constitute a waiver by such Party to require strict and punctual compliance with each and every provision of this Agreement.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 107.35pt;"><span lang="EN-GB">22 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>ENTIRE AGREEMENT AND VARIATION</span></h2>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; tab-stops: right 265.5pt;" align="left"><span lang="EN-GB">22.1<span style="mso-spacerun: yes;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>This document embodies the entire Agreement between the </span></p>
<p class="MsoNormal" style="margin-left: 34.0pt; text-indent: 0in;"><span lang="EN-GB">Parties hereto.</span></p>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">22.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>No amendment or variation of any of the provisions of this Agreement shall be of any force or effect unless reduced to writing and signed by both Parties. This requirement shall only be satisfied if such amendment or variation is made in a written, paper-based form. The provisions of the Electronic Transactions Act, 2008 (Act 772) may be excluded from this clause 21 as and when required.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 61.25pt;"><span lang="EN-GB">23 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>ARBITRATION</span></h2>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">23.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Any dispute in connection with this Agreement, including any question regarding its existence,<span style="mso-spacerun: yes;">&nbsp; </span>validity<span style="mso-spacerun: yes;">&nbsp; </span>or termination,<span style="mso-spacerun: yes;">&nbsp; </span>shall be referred to and finally be resolved by arbitration under the Rules of Alternative Dispute Resolution Act, 2010 (Act 798) (the Rules), including the right to appeal, which Rules are deemed to be incorporated by reference into this clause 23.1.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">23.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The number of arbitrator(s) shall be 1, whose identity shall be agreed in writing between the Parties within 7 (seven) Business Days following the declaration of a dispute between the Parties, failing which the arbitrator shall be appointed f in terms of the Rules, taking into account the value and complexity of the dispute under referral.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">23.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The seat, or legal place, of the arbitration shall be Ghana and any hearing shall be held in Accra. The language to be used in the arbitral proceedings shall be English. Unless the parties agree otherwise, the arbitration shall be conducted on an urgent basis in terms of the Rules.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">23.4 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Nothing contained in this clause 23 shall preclude any Party from approaching a court of competent jurisdiction within Ghana for interim relief on an urgent basis pending the final outcome of an arbitration referral under this clause 23.</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">23.5 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The Parties agree and irrevocably undertake to keep the arbitration and all matters related thereto strictly confidential. Each Party (i) acknowledges and agrees that it shall not disclose any such information to any person other than its own employees, members, officers, professional advisors and/or other divisions who need to know such information for the purposes of this clause 23 (<strong style="mso-bidi-font-weight: normal;">Permitted Recipient</strong>) or to third parties where it is required to do so under law or in terms of regulatory process (ii)shall procure that each Permitted Recipient is made aware of and complies with its obligations of confidentiality in terms of this clause 23 and (iii) give reasonable notice to the other Party as and when any obligation for third party disclosure arises.</span></p>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">23.6 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>The provisions of this Agreement shall be governed by and interpreted in accordance with the laws of Ghana.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 86.75pt;"><span lang="EN-GB">24 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>NOTICES AND DOMICILIUM</span></h2>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">24.1 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>All notices to be served under this Agreement shall be in English and shall be served by hand or by facsimile or by registered mail. Service by hand shall be to the addressee&rsquo;s address shown above and shall be effective upon service. Service by facsimile shall be to the last known facsimile number of the addressee and shall be deemed to have been effected on completion of transmission provided confirmation of successful transmission is given by the transmitting machine. Service by registered mail shall be to the addressee&rsquo;s address shown above and shall be deemed to have been served three Business Days after postage. Any notice given in terms of this Agreement shall be in writing and shall:</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">24.1.1<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp; </span>if delivered by hand be deemed to have been duly received by the addressee on the date of delivery;</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">24.1.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>if posted by prepaid registered post be deemed to have been received by the addressee on the 8th Business Day following the date of such posting;</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">24.1.3 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>if transmitted by fax be deemed to have been received by the addressee 1 Business Day after dispatch;</span></p>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB">24.1.4 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp; </span>if sent electronically, shall be deemed to have been received on the first Business Day following the successful transmission thereof as evidenced by the electronic confirmation of receipt (unless the contrary is proven). </span></p>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB">24.2 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Notwithstanding anything to the contrary contained in this Agreement, a written notice or communication actually received by a Party at its chosen domicilium address set out above shall be an adequate written notice of communication to such Party.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 99.3pt;"><span lang="EN-GB">25 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>CERTIFICATE OF INDEBTEDNESS</span></h2>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>A certificate signed by any manager of the Bank (whose capacity and authority need not be proven), will on its mere production, be sufficient proof of the matters stated therein, except where there is obvious error.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 67.05pt;"><span lang="EN-GB">26 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>COUNTERPARTS</span></h2>
<p class="MsoNormal" style="margin: 0in 0in 9.8pt 33.75pt;"><span lang="EN-GB"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>This Agreement may be signed in counterparts and the copies signed in counterpart shall constitute the Agreement.</span></p>
<h2 style="margin-left: -.75pt; text-indent: 0in; tab-stops: center 47.8pt;"><span lang="EN-GB">27 <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>COSTS</span></h2>
<p class="MsoNormal" style="margin-left: 33.75pt;"><span lang="EN-GB"><span style="mso-spacerun: yes;">&nbsp;</span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Each Party shall pay its own cost of negotiating, drafting, preparing and implementing this Agreement.</span></p>
</div>
<p class="MsoNormal"><span lang="EN-GB">&nbsp;</span></p>
<h1 style="margin: 0in 0in 7.0pt -.25pt;"><span lang="EN-GB">APPENDIX 1 CASH COLLECTION PROCEDURE</span></h1>
<p class="MsoNormal" style="margin-bottom: 10.0pt; mso-list: l2 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="EN-GB" style="mso-bidi-font-size: 8.0pt; line-height: 105%;"><span style="mso-list: Ignore;">1<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><span lang="EN-GB">Prior to the arrival of the Bank, the Customer shall sort the Cash into bundles of denominations and coins as agreed with the Bank from time to time and place the Cash bundles in a Cash collection box provided by the Bank.</span></p>
<p class="MsoNormal" style="margin-bottom: 10.2pt; mso-list: l2 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="EN-GB" style="mso-bidi-font-size: 8.0pt; line-height: 105%;"><span style="mso-list: Ignore;">2<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><span lang="EN-GB">The Customer shall record the amount of Cash collected on a blank page of the Deposit Book.</span></p>
<p class="MsoNormal" style="margin-bottom: 9.65pt; line-height: 102%; mso-list: l2 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="EN-GB" style="mso-bidi-font-size: 8.0pt; line-height: 102%;"><span style="mso-list: Ignore;">3<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><span lang="EN-GB">The Carrier shall take delivery of the Cash collection box and the Deposit Book from the Customer.<span style="mso-spacerun: yes;">&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp; </span></span></p>
<p class="MsoNormal" style="text-indent: .5in; line-height: 102%; margin: 0in 0in 9.65pt 0in;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">a</span></strong><span lang="EN-GB"> <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Apply the seal.<span style="mso-spacerun: yes;">&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></p>
<p class="MsoNormal" style="text-indent: .5in; line-height: 102%; margin: 0in 0in 9.65pt 0in;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">b</span></strong><span lang="EN-GB"> <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Take delivery of the cash collection box and deposit book from the Customer.<span style="mso-spacerun: yes;">&nbsp;&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp; </span></span></p>
<p class="MsoNormal" style="text-indent: .5in; line-height: 102%; margin: 0in 0in 9.65pt 0in;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">c</span></strong><span lang="EN-GB"> <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Record the seal number on the log sheet.<span style="mso-spacerun: yes;">&nbsp; </span><span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></p>
<p class="MsoNormal" style="text-indent: .5in; line-height: 102%; margin: 0in 0in 9.65pt 0in;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">d</span></strong><span lang="EN-GB"> <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Sign the log sheet. </span></p>
<p class="MsoNormal" style="margin-bottom: 9.3pt; mso-list: l2 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="EN-GB" style="mso-bidi-font-size: 8.0pt; line-height: 105%;"><span style="mso-list: Ignore;">4<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><span lang="EN-GB">The Carrier shall stamp all copies of the relevant page(s) of the Deposit Book with the stamp issued by the Bank for the purpose and shall thereafter return the Deposit Book with the duplicate or the second (2nd) copy to the Customer.<span style="mso-spacerun: yes;">&nbsp; </span></span></p>
<p class="MsoNormal" style="margin-bottom: 16.25pt; mso-list: l2 level1 lfo2;"><!-- [if !supportLists]--><strong><span lang="EN-GB" style="mso-bidi-font-size: 8.0pt; line-height: 105%;"><span style="mso-list: Ignore;">5<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><span lang="EN-GB">The Carrier shall promptly thereafter depart from the Site with the sealed cash collection box, stamped top copy or original of deposit book and log sheet. </span></p>
<p><span lang="EN-GB" style="font-size: 8.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial; color: #0066b3; mso-ansi-language: EN-GB; mso-fareast-language: EN-GB; mso-bidi-language: AR-SA;">&nbsp;</span></p>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; margin: 0in 0in 8.0pt 0in;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">&nbsp;</span></strong></p>
<p class="MsoNormal" style="text-indent: 0in; margin: 0in 0in 13.4pt -.75pt;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB" style="font-size: 12.0pt; line-height: 105%;">APPENDIX 2- FEES FOR THE PROVISION OF SERVICES BY THE BANK </span></strong></p>
<p class="MsoNormal" style="text-indent: 0in; margin: 0in 0in 13.4pt 0in;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">&nbsp;</span></strong></p>
<table class="MsoNormalTable" style="width: 424.75pt; border-collapse: collapse; mso-yfti-tbllook: 1184; mso-padding-alt: 0in 0in 0in 0in;" border="0" width="566" cellspacing="0" cellpadding="0">
<tbody>
<tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes; height: 28.35pt;">
<td style="width: 127.1pt; border: solid windowtext 1.0pt; padding: 0in 5.4pt 0in 5.4pt; height: 28.35pt;" valign="top" width="169">
<p class="MsoNormal"><a name="_Hlk107906557"></a><strong><span lang="EN-GB" style="mso-fareast-language: EN-US;">SERVICE </span></strong></p>
<p class="MsoNormal"><span style="mso-bookmark: _Hlk107906557;"><strong><span lang="EN-GB" style="mso-fareast-language: EN-US;">(Collections)</span></strong></span></p>
</td>
<td style="width: 141.75pt; border: solid windowtext 1.0pt; border-left: none; padding: 0in 5.4pt 0in 5.4pt; height: 28.35pt;" valign="top" width="189">
<p class="MsoNormal"><span style="mso-bookmark: _Hlk107906557;"><strong><span lang="EN-GB" style="mso-fareast-language: EN-US;">RATE PER PICK(GHS) </span></strong></span></p>
</td>
<td style="width: 155.9pt; border: solid windowtext 1.0pt; border-left: none; padding: 0in 0in 0in 0in; height: 28.35pt;" valign="top" width="208">
<p class="MsoNormal"><span style="mso-bookmark: _Hlk107906557;"><strong><span lang="EN-GB" style="mso-fareast-language: EN-US;">TRANSPORT COST PER KM (GHS)</span></strong></span></p>
</td>
</tr>
<tr style="mso-yfti-irow: 1; mso-yfti-lastrow: yes; height: 28.35pt;">
<td style="width: 127.1pt; border: solid windowtext 1.0pt; border-top: none; padding: 0in 5.4pt 0in 5.4pt; height: 28.35pt;" valign="top" width="169">
<p class="MsoNormal"><span style="mso-bookmark: _Hlk107906557;"><span lang="EN-GB" style="mso-fareast-language: EN-US;">&nbsp;</span></span></p>
<p class="MsoNormal"><span style="mso-bookmark: _Hlk107906557;"><span lang="EN-GB" style="mso-fareast-language: EN-US;">Armoured/ Bullet-Proof <span style="mso-spacerun: yes;">&nbsp;</span>Vehicle*</span></span></p>
</td>
<td style="width: 141.75pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0in 5.4pt 0in 5.4pt; height: 28.35pt;" valign="top" width="189">
<p class="MsoNormal" style="margin-left: 0in; text-indent: 0in;"><span style="mso-bookmark: _Hlk107906557;"><strong><span lang="EN-GB" style="mso-fareast-language: EN-US;">56</span></strong></span></p>
</td>
<td style="width: 155.9pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0in 0in 0in 0in; height: 28.35pt;" valign="top" width="208">
<p class="MsoNormal"><span style="mso-bookmark: _Hlk107906557;"><strong><span lang="EN-GB" style="mso-fareast-language: EN-US;"><span style="mso-spacerun: yes;">&nbsp; </span>404</span></strong></span></p>
</td>
</tr>
</tbody>
</table>
<p class="MsoNormal" style="text-indent: 0in; margin: 0in 0in 13.4pt -.75pt;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">&nbsp;</span></strong></p>
<p class="MsoNormal" style="text-indent: 0in; margin: 0in 0in 13.4pt -.75pt;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">* subject to the Customer&rsquo;s written request, weekdays include days officially declared as public holidays in Ghana</span></strong></p>
<p class="MsoNormal" style="text-indent: 0in; margin: 0in 0in 13.4pt -.75pt;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">&nbsp;</span></strong></p>
<p class="MsoNormal" style="text-indent: 0in; margin: 0in 0in 13.4pt -.75pt;"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">IN WITNESS</span></strong><span lang="EN-GB"> whereof the parties hereto have caused their authorized representatives to set their hands the day and year first above written.</span></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-indent: 0in;"><span lang="EN-GB">Signed for and on behalf of </span></p>
<h2 style="margin: 0in 0in 38.15pt -.25pt;"><span lang="EN-GB">STANBIC BANK GHANA LTD</span></h2>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; margin: 0in 0in 2.6pt 0in;" align="left"><span lang="EN-GB">&nbsp;</span></p>
<h2 style="text-indent: 0in; tab-stops: center 326.25pt; margin: 0in 0in 3.55pt -.75pt;"><span lang="EN-GB">Authorised Signatory <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Authorised Signatory </span></h2>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; tab-stops: center 297.8pt; margin: 0in 0in 46.6pt -.75pt;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">Name:<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Name:</span></strong></p>
<p class="MsoNormal" style="text-indent: 0in; margin: 0in 0in 39.45pt -.75pt;"><span lang="EN-GB">In the presence of:- </span></p>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; margin: 0in 0in 2.6pt 0in;" align="left"><span lang="EN-GB">&nbsp;</span></p>
<h2 style="text-indent: 0in; tab-stops: center 300.9pt; margin: 0in 0in 3.55pt -.75pt;"><span lang="EN-GB">Witness <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Witness </span></h2>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; tab-stops: center 297.8pt; margin: 0in 0in 44.8pt -.75pt;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">Name:<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Name:</span></strong></p>
<p class="MsoNormal" style="margin-left: -.75pt; text-indent: 0in;"><span lang="EN-GB">Signed for and on behalf of </span></p>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 512%; tab-stops: 36.1pt; margin: 0in 382.45pt 0in 0in;" align="left"><span lang="EN-GB"><!-- [if !supportAnnotations]--><a id="_anchor_1" class="msocomanchor" href="#_msocom_1" name="_msoanchor_1">[AMATA1]</a><!--[endif]--><span style="mso-special-character: comment;">&nbsp;</span></span></p>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 512%; tab-stops: 36.1pt; margin: 0in 382.45pt 0in 0in;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">Name:</span></strong></p>
<h2 style="text-indent: 0in; tab-stops: center 326.25pt; margin: 0in 0in 3.55pt -.75pt;"><span lang="EN-GB">Authorised Signatory <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Authorised Signatory </span></h2>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; tab-stops: center 297.8pt; margin: 0in 0in 43.65pt -.75pt;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">Name:<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Name:</span></strong></p>
<p class="MsoNormal" style="text-indent: 0in; margin: 0in 0in 36.7pt -.75pt;"><span lang="EN-GB">In the presence of:- </span></p>
<p class="MsoNormal" style="text-align: left; text-indent: 0in; line-height: 107%; margin: 0in 0in 2.6pt 0in;" align="left"><span lang="EN-GB">&nbsp;</span></p>
<h2 style="text-indent: 0in; tab-stops: center 300.9pt; margin: 0in 0in 3.55pt -.75pt;"><span lang="EN-GB">Witness <span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Witness </span></h2>
<p class="MsoNormal" style="margin-left: -.75pt; text-align: left; text-indent: 0in; line-height: 107%; tab-stops: center 297.8pt;" align="left"><strong style="mso-bidi-font-weight: normal;"><span lang="EN-GB">Name:<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Name:</span></strong></p>
<div style="mso-element: comment-list;"><!-- [if !supportAnnotations]--><hr class="msocomoff" align="left" size="1" width="33%"><!--[endif]-->
<div style="mso-element: comment;"><!-- [if !supportAnnotations]-->
<div id="_com_1" class="msocomtxt"><!--[endif]--><span style="mso-comment-author: 'Amponsah-Mensah\, Akosua Tweneboa A'; mso-comment-providerid: AD; mso-comment-userid: 'S::Amponsah-MensahA\@stanbic\.com\.gh::071c80a5-b08d-433e-bf21-0d1d658581cb';"><!-- [if !supportAnnotations]--><a name="_msocom_1"></a><!--[endif]--></span>
<p class="MsoCommentText"><span lang="EN-GB" style="font-size: 8.0pt;"><span style="mso-special-character: comment;">&nbsp;<!-- [if !supportAnnotations]--><a class="msocomoff" href="#_msoanchor_1">[AMATA1]</a><!--[endif]--></span></span><span lang="EN-GB">Name of the Customer </span></p>
<!-- [if !supportAnnotations]--></div>
<!--[endif]--></div>
</div>
    `
  );

  editorConfig: EditorComponent['init'] = {
    base_url: '/tinymce',
    suffix: '.min',
    branding: false,
    promotion: false,
    menubar: true,
    height: 700,
    license_key: 'gpl',
    plugins: 'lists link image paste table code help wordcount',
    toolbar:
      'undo redo | blocks | bold italic | alignleft aligncenter alignright | indent outdent | bullist numlist | code | help',
  };
}
